# Generated by Django 4.1.5 on 2023-05-17 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lecturer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturer",
            name="is_admin",
        ),
    ]
