# Generated by Django 4.2 on 2023-04-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id_class', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
            ],
        ),
    ]
