# Generated by Django 4.1.5 on 2023-04-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id_class', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
                ('id_lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.lecturer')),
            ],
        ),
    ]
