# Generated by Django 4.2 on 2023-04-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class', '0001_initial'),
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='id_lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.lecturer'),
        ),
    ]
