# Generated by Django 4.1.5 on 2023-05-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0001_initial"),
        ("Class", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="id_faculty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="faculty.faculty",
            ),
            preserve_default=False,
        ),
    ]
